# This file was generated by GoReleaser. DO NOT EDIT.
class Golab < Formula
  desc "A command-line tool for gitlab"
  homepage "https://github.com/cloudingcity/golab"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cloudingcity/golab/releases/download/v0.3.0/golab_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "0715e760cf4c9978a2aece97d121c2e18e088ad6066e3610565567befed00fea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cloudingcity/golab/releases/download/v0.3.0/golab_0.3.0_Linux_x86_64.tar.gz"
      sha256 "cdb39e2bc5d64d381a0503272c7b561590cd469960a378c0b039a7603d2b11b1"
    end
  end
  
  depends_on "git"

  def install
    bin.install "golab"
  end
end
