# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gool < Formula
  desc "A toolkit make your programmer life easier"
  homepage "https://github.com/cloudingcity/gool"
  version "0.11.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudingcity/gool/releases/download/v0.11.0/gool_0.11.0_Darwin_x86_64.tar.gz"
      sha256 "3148efb0224ed425ac3951e17402f727653a5167b1c435fc0a25732e54124a2b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudingcity/gool/releases/download/v0.11.0/gool_0.11.0_Darwin_arm64.tar.gz"
      sha256 "6e54c5819cf0541cf0babba1412b379805b4df0b4d44a6f0a246a02de8d3eb59"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudingcity/gool/releases/download/v0.11.0/gool_0.11.0_Linux_x86_64.tar.gz"
      sha256 "343e11625b76d27411749bb946175464a1299fbe9c4d742403dcdc9723c6a4bc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudingcity/gool/releases/download/v0.11.0/gool_0.11.0_Linux_arm64.tar.gz"
      sha256 "aa4ae3a96089480f449efd615de4725c3fc055a7741d1419090f36b2f9e1286f"
    end
  end

  def install
    bin.install "gool"
  end
end
