# This file was generated by GoReleaser. DO NOT EDIT.
class Gool < Formula
  desc "A toolkit make your programmer life easier"
  homepage "https://github.com/cloudingcity/gool"
  version "0.9.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cloudingcity/gool/releases/download/v0.9.0/gool_0.9.0_Darwin_x86_64.tar.gz"
    sha256 "dbd2f734f216226eb1a34cedfde897612887855ce4e56e54184a3b2296d5544e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cloudingcity/gool/releases/download/v0.9.0/gool_0.9.0_Linux_x86_64.tar.gz"
    sha256 "a081543e7f79a84584335c04c70fee5dee02cb51e03eb81e574b343d187028dd"
  end

  def install
    bin.install "gool"
  end
end
