# This file was generated by GoReleaser. DO NOT EDIT.
cask "gool" do
  desc "A Go-based CLI toolkit for common developer tasks"
  homepage "https://github.com/cloudingcity/gool"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gool"

  on_macos do
    on_intel do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.10/gool_Darwin_x86_64.tar.gz"
      sha256 "4ed1057eb7affc4d2c3b94dc54d4ee47f9b9a7ce71f3d7b805ec8d73ef41bc2d"
    end
    on_arm do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.10/gool_Darwin_arm64.tar.gz"
      sha256 "9aa6f0705ceec12a3c243a4768b4c23a02093100a300910150bd84361d119ebf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.10/gool_Linux_x86_64.tar.gz"
      sha256 "029c6252294f459a5e50ad2e6b799cb8e6cf1f4bbbb08a9abe6801a842e23703"
    end
    on_arm do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.10/gool_Linux_arm64.tar.gz"
      sha256 "97863fe098779c90505051003b08315d92c517a7dcee27f8261a1f8e5932e043"
    end
  end

  # No zap stanza required
end
