# This file was generated by GoReleaser. DO NOT EDIT.
cask "gool" do
  desc "A Go-based CLI toolkit for common developer tasks"
  homepage "https://github.com/cloudingcity/gool"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gool"

  on_macos do
    on_intel do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.1/gool_Darwin_x86_64.tar.gz"
      sha256 "ec8dff1b20bfc6407983287de2e80e265db37f4fdfb906ffabbb9c15e8407470"
    end
    on_arm do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.1/gool_Darwin_arm64.tar.gz"
      sha256 "2ab72359ac9206ca9d8291cbfe87b07acb0122ba63790b0dec90c1d607d50c18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.1/gool_Linux_x86_64.tar.gz"
      sha256 "aa97fc7f15aa407c344f2aa363a2104e8bd89c4a46dd7aab9577edc8e93ca259"
    end
    on_arm do
      url "https://github.com/cloudingcity/gool/releases/download/v1.0.1/gool_Linux_arm64.tar.gz"
      sha256 "4e28a695279b415c8c0c4e60a0365e0a4982e139ff3d0e98bd77e2c0351ceda0"
    end
  end

  # No zap stanza required
end
